### ISSUE TITLE
sd_modify_user_table_row Function Need to be updated

### ISSUE THREAD

**Issue by prafulkalpund** [seb86/users-by-date-registered#10]
After the "if" condition you need to return the $val as it is a filter

function sd_modify_user_table_row($val, $column_name, $user_id)
{
    $user = get_userdata($user_id);

    if ($column_name === 'registered') {
        $t_time    = get_the_time(__('Y/m/d g:i:s a'));
        $m_time    = $user->user_registered;
        $time      = mysql2date('G', $m_time, false);

        $time_diff = time() - $time;

        // Get the last 7 days.
        $days = ( intval($time_diff) / DAY_IN_SECONDS ) % 8;
        $days = $days * -1; // Convert negative value to positive.

        if ($days > 0 && $days < 8) {
            /* translators: Number of days */
            $h_time = sprintf(__('%s days ago', 'users-by-date-registered'), $days);
        } else {
            $h_time = mysql2date(get_option('date_format'), $m_time);
        }

        return '<abbr title="' . $t_time . '">' . apply_filters('user_registered_date_column_time', $h_time, $user) . '</abbr>';
    }
    
    return $val;
}

**Comment by seb86** [comment]
Thank you for reporting this. It was removed by mistake during the last release when re-writing the function. I will add it back.
