### ISSUE TITLE
Not Working with PHP7

### ISSUE THREAD

**Issue by foxpcteam** [seb86/Users-by-Date-Registered#3]
Hi,
after update php version to php7 i start getting this error:
`PHP Parse error:  Invalid numeric literal on line 178`

can you provide fix?

Thanks

**Comment by seb86** [comment]
I have just seen this error myself. Not sure how to fix it at the moment. [Why that line?](https://github.com/seb86/Users-by-Date-Registered/blob/master/users-by-date-registered.php#L178) I will do some research it.

**Comment by seb86** [comment]
Fixed.
