### ISSUE TITLE
Searching a user returns empty

### ISSUE THREAD

**Issue by seb86** [seb86/Users-by-Date-Registered#5]
No results are returned when searching for an existing user.

**Comment by dnspnjrs** [comment]
@seb86 yes i have this problem too. it makes this plugin unusable unfortunately.

Do you have any idea how to fix it? 

Thanks in advance.

**Comment by ahberg** [comment]
I made a version that support search 
https://github.com/ahberg/Users-by-Date-Registered

**Comment by seb86** [comment]
@ahberg It is a bit difficult to see what changes you have made specifically as all I see mostly is that you have altered the spacing.

**Comment by robertstaddon** [comment]
I was having the same issue with the user search returning blank and can verify that installing the version from @ahberg solved the problem.
