### ISSUE TITLE
Other sortable columns turned off

### ISSUE THREAD

**Issue by benbranyon** [seb86/users-by-date-registered#8]
Hello.  I've noticed that this plugin will turn off the other sortable columns in the User's table. You should be able to fix this by adding the Date Registered field to the columns that already exist instead of overriding it. I can fork and help fix this if you'd like.

**Comment by benbranyon** [comment]
`/**
 * Allows you to sort the users table by date order.
 *
 * @since  1.0.0
 * @return array
 */
function sd_get_sortable_columns( $columns ) {
	$columns['registered'] = __( 'Date Registered', 'users-by-date-registered' );

	return $columns;	
} // END sd_get_sortable_columns()
add_filter( 'manage_users_sortable_columns', 'sd_get_sortable_columns' );`

**Comment by benbranyon** [comment]
Above works for me on my WP install using this plugin

**Comment by benbranyon** [comment]
I sent you a pull request with this change as well.

**Comment by seb86** [comment]
Thank you for spotting the error. I will look into this.

**Comment by seb86** [comment]
@benbranyon What you pushed was not entirely accurate so I have [adjusted it](https://github.com/seb86/users-by-date-registered/blob/master/users-by-date-registered.php#L81,L84) myself and still credited you for the find.

Again, thank you for your contribution.

**Comment by benbranyon** [comment]
Awesome. Thanks for looking into that so quickly.
